server:
  port: 8090
  session-timeout: 60

security.basic.enabled: false
endpoints.shutdown.enabled: true

spring.profiles.active: preprobd
spring.profiles.include: googlestorage,devmail

---
spring:
  profiles: devbd

  jpa:
    showSql: true
    dataBase: H2
    hibernate.generateDdl: true

backend:
  admin:
    username: backendadmin
    password: betuzo
    backend.admin.role: BACKEND_ADMIN

---
spring:
  profiles: preprobd

  jpa:
    showSql: false
    dataBase: POSTGRESQL
    hibernate.generateDdl: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-174-129-254-238.compute-1.amazonaws.com:5432/dftdi5j68bdo18?sslmode=require
    username: merkafwrbknkbs
    password:  9ef5b2c6894e2d259e210a40d1577cf33504242e0337ca96b55641bed63fac4c

backend:
  admin:
    username: backendadmin
    password: betuzo
    backend.admin.role: BACKEND_ADMIN

---
spring:
  profiles: googlestorage

lupa:
  web.pathPhoto: photo/
  service.google:
    bucketName: sis-lupa-img
    pathWeb: https://storage.googleapis.com/sis-lupa-img/

---
spring:
  profiles: localbmvstorage

lupa.web.pathPhoto: /home/betuzo/opt/photo/

---
spring:
  profiles: localhomestorage

lupa.web.pathPhoto: /Users/betuzo/opt/photo/

---
spring:
  profiles: devmail

mail:
  host: smtp.gmail.com
  port: 587
  username: betotsol@gmail.com
  password: soymuyflojo
  from.default: notificacion@lupa.com
  to.default: notificacion@lupa.com
  subject.default: Notificacion lupa
  smtp:
    auth: true
    starttls.enable: true
